name: Static Analysis

# Run on all push and pull requests
on:
  push:
    branches:
      - dev
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  static-analysis:
    name: Static Analysis
    uses: nasa/cFS/.github/workflows/app-static-analysis-reusable.yml@dev
